String.toLocaleString(
{
	"en":
	{
		"Layers": "Layers",
		"Traffic": "Traffic",
		"Transit": "Transit",
		"StreetView": "StreetView",
		"Weather": "Weather",
		"Clouds": "Clouds",
		"Position": "Position",
		"Address": "Address",
		"Informations": "Informations",
		"Date": "Date",
		"Title": "Title",
		"Save": "Save",
		"Reset": "Reset",
		"Search": "Search",
		"Find": "Find",
		"Close": "Close",
		"Filter": "Filter",
		"Local": "Local",
		"Current": "Current",
		"Location": "Location",
		"Actual": "Actual",
		"Reduce": "Reduce",
		"Detail": "Detail",
		"Cancel": "Cancel",
		"Link": "Link",
		"Restart": "Restart",
		"Save marker data": "Save marker data",
		"Reset marker data": "Reset marker data",
		"Close marker editor": "Close marker editor",
		"Change marker date": "Change marker date",
		"Actual location": "Actual location",
		"Current location": "Current location", 
		"Center map": "Center map",
		"Center map here": "Center map here",
		"Show panorama": "Show panorama",
		"Show panorama here": "Show panorama here",
		"Close panorama": "Close panorama",
		"Add marker": "Add marker",
		"Add marker here": "Add marker here",
		"Edit marker": "Edit marker",
		"Edit this marker": "Edit this marker",
		"Delete marker": "Delete marker",
		"Delete this marker": "Delete this marker",
		"Search position": "Search position",
		"Search by location": "Search by location",
		"Search position data": "Search position data",
		"Search marker location data": "Search marker location data",
		"Alter division": "Alter division",
		"Toggle full screen mode": "Toggle full screen mode",
		"Toggle division between map and panorama": "Toggle division between map and panorama",
		"Public interface": "Public interface",
		"Authenticated interface": "Authenticated interface",
		"OAuth2 interface": "OAuth2 interface",
		"Marker filter": "Marker filter",
		"Filter markers": "Filter markers",
		"Move marker": "Move marker",
		"Move": "Move",
		"Logout": "Logout",
		"Change": "Change",
		"Sunday": "Sunday",
		"Monday": "Monday",
		"Tuesday": "Tuesday",
		"Wednesday": "Wednesday",
		"Thursday": "Thursday",
		"Friday": "Friday",
		"Saturday": "Saturday",
		"Sun": "Sun",
		"Mon": "Mon",
		"Tue": "Tue",
		"Wed": "Wed",
		"Thu": "Thu",
		"Fri": "Fri",
		"Sat": "Sat",
		"January": "January",
		"February": "February",
		"March": "March",
		"April": "April",
		"May": "May",
		"June": "June",
		"July": "July",
		"August": "August",
		"September": "September",
		"October": "October",
		"November": "November",
		"December": "December",
		"Jan": "Jan",
		"Feb": "Feb",
		"Mar": "Mar",
		"Apr": "Apr",
		"May_s": "May",
		"Jun": "Jun",
		"Jul": "Jul",
		"Aug": "Aug",
		"Sep": "Sep",
		"Oct": "Oct",
		"Nov": "Nov",
		"Dec": "Dec",
		"About the calendar": "About the calendar",
		"Prev. year (hold for menu)": "Prev. year (hold for menu)",
		"Prev. month (hold for menu)": "Prev. month (hold for menu)",
		"Go Today": "Go Today",
		"Next month (hold for menu)": "Next month (hold for menu)",
		"Next year (hold for menu)": "Next year (hold for menu)",
		"Select date": "Select date",
		"Drag to move": "Drag to move",
		" (today)": " (today)",
		"Display %s first": "Display %s first",
		"0,6": "0,6",
		"Today": "Today",
		"(Shift-)Click or drag to change value": "(Shift-)Click or drag to change value",
		"%Y-%m-%d": "%Y-%m-%d",
		"%a, %b %e": "%a, %b %e",
		"wk": "wk",
		"Time:": "Time:",
		"DHTML Date/Time Selector\n(c) dynarch.com 2002-2005 / Author: Mihai Bazon\nFor latest version visit: http://www.dynarch.com/projects/calendar/\nDistributed under GNU LGPL.  See http://gnu.org/licenses/lgpl.html for details.\n\nDate selection:\n- Use the \xab, \xbb buttons to select year\n- Use the \u2039, \u203a buttons to select month\n- Hold mouse button on any of the above buttons for faster selection.": "DHTML Date/Time Selector\n(c) dynarch.com 2002-2005 / Author: Mihai Bazon\nFor latest version visit: http://www.dynarch.com/projects/calendar/\nDistributed under GNU LGPL.  See http://gnu.org/licenses/lgpl.html for details.\n\nDate selection:\n- Use the \xab, \xbb buttons to select year\n- Use the \u2039, \u203a buttons to select month\n- Hold mouse button on any of the above buttons for faster selection.",
		"\n\nTime selection:\n- Click on any of the time parts to increase it\n- or Shift-click to decrease it\n- or click and drag for faster selection.": "\n\nTime selection:\n- Click on any of the time parts to increase it\n- or Shift-click to decrease it\n- or click and drag for faster selection."
	},

	"pt":
	{
		"Layers": "Camadas",
		"Traffic": "Tráfego",
		"Transit": "Trânsito",
		"StreetView": "Panoramas",
		"Weather": "Tempo",
		"Clouds": "Nuvens",
		"Position": "Posição",
		"Address": "Endereço",
		"Informations": "Informações",
		"Date": "Data",
		"Title": "Título",
		"Save": "Salvar",
		"Reset": "Restaurar",
		"Search": "Pesquisa",
		"Find": "Buscar",
		"Close": "Fechar",
		"Filter": "Filtro",
		"Local": "Local",
		"Current": "Atual",
		"Location": "Localização",
		"Actual": "Atual",
		"Reduce": "Reduzir",
		"Detail": "Detalhar",
		"Cancel": "Cancelar",
		"Link": "Link",
		"Restart": "Reiniciar",
		"Save marker data": "Salvar dados de marcador",
		"Reset marker data": "Restaurar dados de marcador",
		"Close marker editor": "Fechar editor de marcador",
		"Change marker date": "Alterar data do marcador",
		"Actual location": "Localização atual",
		"Current location": "Localização atual", 
		"Center map": "Centralizar mapa",
		"Center map here": "Centralizar mapa aqui",
		"Show panorama": "Mostrar panorama",
		"Show panorama here": "Mostrar panorama aqui",
		"Close panorama": "Fechar panorama",
		"Add marker": "Adicionar marcador",
		"Add marker here": "Adicionar marcador aqui",
		"Edit marker": "Editar marcador",
		"Edit this marker": "Editar este marcador",
		"Delete marker": "Apagar marcador",
		"Delete this marker": "Apagar este marcador",
		"Search position": "Pesquisar posição",
		"Search by location": "Pesquisa por local",
		"Search position data": "Pesquisar local desta posição",
		"Search marker location data": "Pesquisar endereço deste marcador",
		"Alter division": "Alterar divisão",
		"Toggle full screen mode": "Alternar modo de tela cheia",
		"Toggle division between map and panorama": "Alternar divisão entre mapa e panorama",
		"Public interface": "Interface p&uacute;blica",
		"Authenticated interface": "Interface autenticada",
		"OAuth2 interface": "Interface oauth2",
		"Marker filter": "Filtro de marcadores",
		"Filter markers": "Filtre marcadores",
		"Move marker": "Mover marcador",
		"Move": "Mover",
		"Logout": "Sair",
		"Change": "Alterar",
		"Sunday": "Domingo",
		"Monday": "Segunda",
		"Tuesday": "Terca",
		"Wednesday": "Quarta",
		"Thursday": "Quinta",
		"Friday": "Sexta",
		"Saturday": "Sabado",
		"Sun": "Dom",
		"Mon": "Seg",
		"Tue": "Ter",
		"Wed": "Qua",
		"Thu": "Qui",
		"Fri": "Sex",
		"Sat": "Sab",
		"January": "Janeiro",
		"February": "Fevereiro",
		"March": "Marco",
		"April": "Abril",
		"May": "Maio",
		"June": "Junho",
		"July": "Julho",
		"August": "Agosto",
		"September": "Setembro",
		"October": "Outubro",
		"November": "Novembro",
		"December": "Dezembro",
		"Jan": "Jan",
		"Feb": "Fev",
		"Mar": "Mar",
		"Apr": "Abr",
		"May_s": "Mai",
		"Jun": "Jun",
		"Jul": "Jul",
		"Aug": "Ago",
		"Sep": "Set",
		"Oct": "Out",
		"Nov": "Nov",
		"Dec": "Dez",
		"About the calendar": "Sobre o calendario",
		"Prev. year (hold for menu)": "Ant. ano (segure para menu)",
		"Prev. month (hold for menu)": "Ant. mes (segure para menu)",
		"Go Today": "Hoje",
		"Next month (hold for menu)": "Prox. mes (segure para menu)",
		"Next year (hold for menu)": "Prox. ano (segure para menu)",
		"Select date": "Selecione a data",
		"Drag to move": "Arraste para mover",
		" (today)": " (hoje)",
		"Display %s first": "Mostre %s primeiro",
		"0,6": "0,6",
		"Today": "Hoje",
		"(Shift-)Click or drag to change value": "(Shift-)Click ou arraste para mudar valor",
		"%Y-%m-%d": "%d/%m/%Y",
		"%a, %b %e": "%a, %e %b",
		"wk": "sm",
		"Time:": "Hora:",
		"DHTML Date/Time Selector\n(c) dynarch.com 2002-2005 / Author: Mihai Bazon\nFor latest version visit: http://www.dynarch.com/projects/calendar/\nDistributed under GNU LGPL.  See http://gnu.org/licenses/lgpl.html for details.\n\nDate selection:\n- Use the \xab, \xbb buttons to select year\n- Use the \u2039, \u203a buttons to select month\n- Hold mouse button on any of the above buttons for faster selection.": "DHTML Date/Time Selector\n(c) dynarch.com 2002-2005 / Author: Mihai Bazon\nUltima versao visite: http://www.dynarch.com/projects/calendar/\nDistribuido sobre GNU LGPL.  Veja http://gnu.org/licenses/lgpl.html para detalhes.\n\nSelecao de data:\n- Use os botoes \xab, \xbb para selecionar o ano\n- Use os botoes \u2039, \u203a para selecionar o mes\n- Segure o botao do mouse em qualquer um desses botoes para selecao rapida.",
		"\n\nTime selection:\n- Click on any of the time parts to increase it\n- or Shift-click to decrease it\n- or click and drag for faster selection.": "\n\nSelecao de hora:\n- Clique em qualquer parte da hora para incrementar\n- ou Shift-click para decrementar\n- ou clique e segure para selecao rapida."
	}
}
);
